options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-madhav:latest', '.']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/todo-madhav:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud container clusters get-credentials sumit-cluster-1 --zone us-central1-c --project sumit-project-422112
      curl -LO https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
      tar -zxvf helm-v3.6.3-linux-amd64.tar.gz
      mv linux-amd64/helm /usr/local/bin/helm
      helm version
      helm upgrade --install todo-madhav ./helm/todo-madhav
