options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 0: Configure Docker authentication
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #         echo Y | gcloud auth configure-docker gcr.io

  # Step 1: Set up the Kubernetes cluster context
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          gcloud container clusters get-credentials sumit-cluster --zone asia-south1-c --project sumit-gcp-practice

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/madhav:latest', '.']

  # Step 3: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/madhav:latest']
